### ISSUE TITLE
Int<->Str typing issue.

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-core#16]
Hi Janis,

I have a wrapper (code below) that takes a string argument to which I wish to pass the string `21`.

As in:
```bash
janis run -o qux view_region.py --bam NA12878.bam --region 21
```

This fails with a stacktrace for the following error:
```
ValueError: There were errors in 1 inputs: {'region': "Value was of type <class 'int'>, expected string"}
```

I expect it's automagically converting the string argument into an int, because it looks like one, and then complaining when the horse has bolted. 

For bonus marks, I tried using YAML for the inputs, and if you use
```yaml
bam: NA12878.bam
region: 20
```
it fails (correctly), but if you use
```yaml
bam: NA12878.bam
region: "20"
```
it succeeds. (There's a subtle round-tripping bug in the main Python YAML implementation, which I can explain if anyone cares, but it relates to integers and quoting.)

The code `view_region.py`:
```python
from typing import List
from janis_core import InputSelector, Filename, String
from janis_core.tool.commandtool import ToolArgument, ToolInput, ToolOutput
from janis_bioinformatics.data_types import Bam, BamBai
from janis_bioinformatics.tools.bioinformaticstoolbase import BioinformaticsTool


class ViewRegion(BioinformaticsTool):
    def tool(self):
        return "ViewRegion"

    def friendly_name(self):
        return "samtools view with region"

    def tool_provider(self):
        return "common"

    def version(self):
        return "0.1.0"

    def container(self):
        return "quay.io/biocontainers/samtools:1.9--h8571acd_11"

    def inputs(self) -> List[ToolInput]:
        return [
            ToolInput("outputFile", Filename, position=3, prefix="-o"),
            ToolInput("bam", BamBai, position=4),
            ToolInput("region", String, position=5)
        ]

    def outputs(self) -> List[ToolOutput]:
        return [ToolOutput("out", Bam, glob=InputSelector("outputFile"))]

    def base_command(self):
        return None

    def arguments(self):
        return [
            ToolArgument("samtools",    position=0, shell_quote=False),
            ToolArgument("view",        position=1, shell_quote=False),
            ToolArgument("-b",          position=2, shell_quote=False),
            # BAM filename goes here.
            # Region goes here.
        ]
```

**Comment by illusional** [comment]
Hi @drtconway, thanks for the report. You're right the janis-assistant was guessing the type based on the value that it provided ([and some order](https://github.com/PMCC-BioinformaticsCore/janis-assistant/blob/3d9d6d6554e2ead99ba26f2517f7661e99871f08/janis_assistant/utils/__init__.py#L110-L134)):

I've added some input value coercion to data types, and now the assistant will attempt to coerce an input value.
