### ISSUE TITLE
potential watch improvement

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-core#17]
Hi Janis,

A possible improvement for `janis watch`:

In scenarios where one is scattering over a step which is itself a workflow, one ends up with many more rows of input that fit on the screen.

A way to reclaim some vertical space would be to collapse the group when all the steps in the sub-workflow have successfully terminated.

In addition, if scattered items that have completed are listed above items with uncompleted steps, the fact that the total number of rows is larger than the screen won't matter so much.

**Comment by illusional** [comment]
Hey @drtconway, this is covered by your `--brief` mode you've added to `janis watch` I believe. Feel free to reopen if it's still an issue.
