### ISSUE TITLE
Fasta File suffixes

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-core#47]
Hi Janis,

I'm getting the following warning:
```
2020-11-12T15:19:18 [WARN]: The input for 'fasta' (FastaFai) did not have the expected extension .fasta OR .fa: /data/reference/dawson_labs/genomes/GRCh38/GCA_000001405.15_GRCh38_full_analysis_set.fna.
```

An extension of `.fna` is pretty wide-spread for FASTA files, and is in some sense even preferable to `.fa` or `.fasta` since it specifically suggests it contains nucleotides (i.e. DNA or RNA) rather than, for example `.faa` which is used to contain amino acids, also in the FASTA format.

It'd be polite of Janis not to produce a warning in this case.

Thanks
Tom.

**Comment by illusional** [comment]
Hi Tom, you're starting to see the start of Janis 0.11.x! There are a heap of really cool changes that are coming soon (and you're hitting a pre-release while accessing `janis/dev`. Some noteworthy things coming up:

- More checks on starting runs (to check your input data is in an expected / correct-ish format). 
- Janis prepare:
  - This also includes checking contigs between Fasta references and Bed Files.
  - Moulding your almost-ready data into what we're expecting (eg: automatic converting VCFs into Compressed VCFs, automatic indexing of references depending on the pipeline).
- Evaluation of submissions to janis-bioinf (to check for correctness)
- Sweet testing suite to test the running of tools.

I've added a [commit to janis-bioinf to add an alternate extension for Fasta](https://github.com/PMCC-BioinformaticsCore/janis-bioinformatics/commit/cc5cca2e3a870873282bde8b9f8d27f8d28debea), and I'll deploy this to the cluster soon.

**Comment by drtconway** [comment]
Cheers!
