### ISSUE TITLE
wanted: janis wait

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-core#50]
Hi Janis,

It'd be really nice to have a command

```
janis wait myworkflowid
```

which waits until the referenced workflow completes.

Bonus marks:
- exit code reflects status of workflow in case of failure.
- multiple workflows can be waited.
- option to restart failed workflows up to some specified number of times
- make a file with the id of the current run `outputdir/janis/id` to make it easy to get the id of the run of interest. It could do one line per attempted run so you can use `tail` to git the run you want to examine.

Partial credit:
- implement it as `janis watch --silent myworkflowid`

Motivation
----------

For reasons of practicality, I have multiple workflows for different parts of a project: alignment, variant calling, copy number, etc. These also get run on different inputs.

It would be nice to be able to write a simple shell script that at least in theory can rerun them all. Assuming no failures, this would make a relatively simple way to document the overall workflow for a large project.

I guess in you could kind of run

```
janis watch myworkflowid > /dev/null 2>&1
```

but that almost certainly does quite a lot more work than necessary.

**Comment by illusional** [comment]
Implemented and released in `v0.11.0`, where `wid` below is the workflow ID or the execution path (usually `<output-dir>/janis`):

```
$ janis wait --help
usage: janis wait [-h] wid [wid ...]

positional arguments:
  wid         Workflows to wait for

optional arguments:
  -h, --help  show this help message and exit
```
