### ISSUE TITLE
add cwl-runner shebang when translating tools

### ISSUE THREAD

**Issue by matthdsm** [PMCC-BioinformaticsCore/janis-core#6]
The cwl standard specifies a shebang for CWL stand alone tools
`#!/usr/bin/env cwl-runner`

Can this be added by default?

Thanks
M

**Comment by illusional** [comment]
Agreed, this is an easy fix for good benefit. Just preparing to respond to your other issue btw :)

**Comment by matthdsm** [comment]
awesome!
Thanks
M
